### PR TITLE
Remove dcraw dependency

### LINKED ISSUE #37: Use thumbnail extraction when possible
This is much faster than using dcraw to generate a tiff and then ImageMagick to convert it to a jpg. The only problem is I don't know the failure mode for images that don't have embedded previews, so I need to learn that before I can actually implement this.

### LINKED ISSUE #55: Fail more gracefully if dcraw isn't present

### PR DESCRIPTION
**Pull request by SamWhited**
Extract the quarter size RGB JPEG from the CR2 files using `rawphoto` instead of dcraw.

Fixes #55 (no longer applicable)
Fixes #37

### CODE REVIEW

**Comment by campaul** [comment]
Now there are no TIFFs

**Comment by SamWhited** [comment]
What do you mean? This is literally doing the exact same thing dcraw was; I didn't look at tiff generation, but this is just getting the blob.

**Comment by campaul** [comment]
So, that code was supposed to be extracting the full thing but through several refactors it got messed up. It's actually extracting the thumbnail, converting it to jpg (because the code for converting tiff to jpg got left over), and then saving that jpg as a tiff (because the code for saving a tiff got left over).

So, that function is supposed to result in .cache getting filled with TIFFs, which it actually does, they're just incorrectly being converted from the JPEGs.

**Comment by SamWhited** [comment]
Ah, that makes sense (I wondered where TIFF generation was being done because I couldn't find it). In that case, I'm going to go ahead and merge this and we can make a separate issue to fix TIFF generation.

**Comment by campaul** [comment]
The tiff generation happens because it's being saved as `.tiff`. If we're going to be using JPGs we should change the path to `.jpg` and just dump the preview straight to disk from rawphoto instead of loading it into an image object and doing 2 conversions to it.

**Comment by campaul** [comment]
Also this means now that we can only do previews and not actual development of the photos.

**Comment by SamWhited** [comment]
@campaul Were you planning on doing development things straight from dcraw on import? I think we'd be better off doing transformations on the tiff files on disk later.

I really hate the idea of calling out to dcraw like this at all, but I can revert if you think it will cause problems later.

**Comment by SamWhited** [comment]
To clarify what I was thinking:

On import we just use the camera generated thumbnail.
If we later decide to do our own processing on import, we use the actual full-sized raw image data and do that processing using whatever library we choose, then save our own thumbnail using Wand.
Once we have a thumbnail, if we make edits to it, the edits are applied to the thumbnail in memory (and maybe flushed to disk depending on how we keep history; that's something for later).
When we export, we extract the full raw-data again, apply the edit history to that, and save it.

I just don't see a reason to use dcraw on the import step for now since we're just fetching a blob either way.

**Comment by campaul** [comment]
So we're going to need TIFFs anyway for doing anything serious. When I export to a PNG, I would like to be exporting from the developed raw and not a JPEG thumbnail. Furthermore, loading the developed TIFF to use as a thumbnail is actually faster than loading a JPEG depending on your equipment, so the only real benefit to using the JPEG thumbnail is we can defer the real development until later and let you look through your photos while that processes in the background.

That being said, I'm ok with doing that to get really fast imports, but we're still going to need dcraw to pull out TIFFs (even if that code isn't written yet) as there are no adequate libraries we can use.

**Comment by SamWhited** [comment]
Oh that's fine, we can convert to TIFF's, I just want the extraction of the data itself to be done by us instead of dcraw.

**Pull request merged**
